before_install:
  - env

branches:
  only:
    - master

language: ruby

matrix:
  allow_failures:
    - rvm: jruby
    - rvm: rbx

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.3
  - 2.4.1
  - jruby
  - rbx

script:
  - bundle exec rake spec

before_install:
  - gem update bundler
